[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

# Compiler settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet-dataseed.bnbchain.org"
bsc_mainnet = "https://bsc-dataseed.binance.org"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
